// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQdnGiOJ-sN94S-Y1WhozrBwYFZFZPv64',
    appId: '1:278942164873:web:e8df844976b05539e06358',
    messagingSenderId: '278942164873',
    projectId: 'mad-pbl-2d434',
    authDomain: 'mad-pbl-2d434.firebaseapp.com',
    storageBucket: 'mad-pbl-2d434.firebasestorage.app',
    measurementId: 'G-ML2DZ178WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiRvxxOKGMPYty44B1gYQa2KaQEJhVGxM',
    appId: '1:278942164873:android:8d6545c48f6347bde06358',
    messagingSenderId: '278942164873',
    projectId: 'mad-pbl-2d434',
    storageBucket: 'mad-pbl-2d434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbN-FXY2BCCpVYoAIcBhM_kvJhohUEczY',
    appId: '1:278942164873:ios:b50cb272c249ea53e06358',
    messagingSenderId: '278942164873',
    projectId: 'mad-pbl-2d434',
    storageBucket: 'mad-pbl-2d434.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbN-FXY2BCCpVYoAIcBhM_kvJhohUEczY',
    appId: '1:278942164873:ios:b50cb272c249ea53e06358',
    messagingSenderId: '278942164873',
    projectId: 'mad-pbl-2d434',
    storageBucket: 'mad-pbl-2d434.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQdnGiOJ-sN94S-Y1WhozrBwYFZFZPv64',
    appId: '1:278942164873:web:727416ce3cf8cdd8e06358',
    messagingSenderId: '278942164873',
    projectId: 'mad-pbl-2d434',
    authDomain: 'mad-pbl-2d434.firebaseapp.com',
    storageBucket: 'mad-pbl-2d434.firebasestorage.app',
    measurementId: 'G-WS0KDHQ31Z',
  );
}
